<?php
/**
 * @file
 * Code for the GSB Feature Alumni Reunion Agenda Item Content Type feature.
 */

include_once 'gsb_feature_alumni_reunion_agenda_item_ct.features.inc';

/**
 * Implements hook_field_extra_fields().
 */
function gsb_feature_alumni_reunion_agenda_item_ct_field_extra_fields() {

  $extra['node']['alumni_reunion_agenda_item']['display']['current_reunion_block'] = array(
    'label' => t('Current Reunion'),
    'description' => t('Current Reunion'),
    'weight' => 30,
  );

  $extra['node']['alumni_reunion_agenda_item']['display']['conditional_stanford_block'] = array(
    'label' => t('Conditional Stanford'),
    'description' => t('Conditional Stanford'),
    'weight' => 31,
  );

  return $extra;
}

/**
 * Implements hook_node_view().
 */
function gsb_feature_alumni_reunion_agenda_item_ct_node_view($node, $view_mode, $langcode) {
  // If this field is not configured for this view mode, skip it.
  $fields = field_extra_fields_get_display('node', $node->type, $view_mode);

  if (!empty($fields['current_reunion_block']['visible'])) {
    $entity_type = 'fieldable_panels_pane';
    $entity_id = '13946';
    $entity = entity_load_single($entity_type, $entity_id);
    $render_array = entity_view($entity_type, array($entity_id => $entity));
    $content = render($render_array);

    $node->content['current_reunion_block'] = array(
      '#type' => 'container',
      '#attributes' => array(
        'class' => array(
          'pane-bundle-links current-reunion-block',
         ),
       ),
       '#children' => $content,
    );
  }

  if (!empty($fields['conditional_stanford_block']['visible'])) {
    if ($node->field_stanford_event['und'][0]['value']) {
      $entity_type = 'fieldable_panels_pane';
      $entity_id = '13926';
      $entity = entity_load_single($entity_type, $entity_id);
      $render_array = entity_view($entity_type, array($entity_id => $entity));
      $content = render($render_array);

      $node->content['conditional_stanford_block'] = array(
        '#type' => 'container',
        '#attributes' => array(
           'class' => array(
            'pane-bundle-links conditional-stanford-block',
           ),
         ),
       '#children' => $content,
      );
    }
  }
}

/**
 * Implements hook_node_insert().
 */
function gsb_feature_alumni_reunion_agenda_item_ct_node_insert($node) {
  _gsb_feature_alumni_reunion_agenda_item_ct_node_save($node);
}

/**
 * Implements hook_node_update().
 */
function gsb_feature_alumni_reunion_agenda_item_ct_node_update($node) {
  _gsb_feature_alumni_reunion_agenda_item_ct_node_save($node);
}

/**
 * Helper for hook_node_insert() and hook_node_update().
 */
function _gsb_feature_alumni_reunion_agenda_item_ct_node_save($node) {
  // Include the pathauto library.
  module_load_include('inc', 'pathauto');

  // if this is not an agenda item, then...
  if ($node->type != 'alumni_reunion_agenda_item') {
    // ... this is not the node we are looking for
    return;
  }

  $group_nids = array();

  // If the agenda item is exclusive only create aliases for those groups.
  if (!empty($node->field_reunion_group_page_ref['und'])) {
    foreach($node->field_reunion_group_page_ref['und'] as $key => $group) {
      $group_nids[] = $group['target_id'];
    }
  }
  else {
    // DB Query to get list of nids for all group pages with a matching session id.
    $results = db_query(
      "Select entity_id from {field_data_field_reunion_session_ref} where field_reunion_session_ref_target_id = " . $node->field_alumni_session_ref['und'][0]['target_id'] . " AND bundle = 'alumni_reunion_group_page'"
    );
    foreach ($results as $record) {
      $group_nids[] = $record->entity_id;
    }
  }

  // Get the session title and clean it for urls.
  $session_nid = $node->field_alumni_session_ref['und'][0]['target_id'];
  $session_node = node_load($session_nid);
  $path = pathauto_cleanstring($session_node->title);

  // Clean the node title.
  $path .= '/' . pathauto_cleanstring($node->title);

  // Loop through the group nodes and create aliases.
  foreach ($group_nids as $group_nid) {
    // Get the alias of the group page.
    $alias_path = drupal_get_path_alias('node/' . $group_nid) . '/' . $path;

    // Check to see if a path alias exists, if not then save it.
    $path_info = path_load(array('alias' => $alias_path));
    if (empty($path_info) || $path_info->source != 'node/' . $node->nid) {
      pathauto_alias_uniquify($alias_path, 'node/' . $node->nid, $node->$language);
      $edit = array(
        'source'   => 'node/' . $node->nid,
        'alias'    => $alias_path,
      );
      path_save($edit);
    }
  }
}

/**
 * Implements hook_ds_pre_render_alter().
 */
function gsb_feature_alumni_reunion_agenda_item_ct_ds_pre_render_alter(&$layout_render_array, $context, &$vars) {

  if ($context['bundle'] == 'alumni_reunion_agenda_item') {

    // Hide the group label if there is more than one group.
    if (isset($layout_render_array['left'])) {
      foreach ($layout_render_array['left'] as $key => $field_info) {
        if ($field_info['#field_name'] == 'field_reunion_group_page_ref' && count($field_info['#items']) > 1) {
          $layout_render_array['left'][$key]['#access'] = FALSE;
          break;
        }
      }
    }
    elseif (isset($layout_render_array['right'])) {
      foreach ($layout_render_array['right'] as $key => $field_info) {
        if ($field_info['#field_name'] == 'field_reunion_group_page_ref' && count($field_info['#items']) > 1) {
          $layout_render_array['right'][$key]['#access'] = FALSE;
          break;
        }
      }
    }
    elseif (isset($layout_render_array['ds_content'])) {
      foreach ($layout_render_array['ds_content'] as $key => $field_info) {
        if ($field_info['#field_name'] == 'field_reunion_group_page_ref' && count($field_info['#items']) > 1) {
          $layout_render_array['ds_content'][$key]['#access'] = FALSE;
          break;
        }
      }
    }

    if ($context['view_mode'] == 'alumni_reunion_agenda_list') {

      // Set the url path to be specific to the current group.

      // Get the alias of the group.
      $group_nid = arg(1);
      $group_alias = drupal_lookup_path('alias', "node/" . $group_nid);
      $node = node_load($group_nid);
      $language = $node->language;

      // Get the alias of the session.
      $session_nid = $node->field_reunion_session_ref[$language][0]['target_id'];
      $session_alias = drupal_lookup_path('alias', "node/" . $session_nid);
      $session_alias = explode('/', $session_alias);

      // Combine them and replace the path to alumni/reunions with the correct
      // path.
      $alias = $group_alias . '/' . $session_alias[1];

      // Include the pathauto library.
      module_load_include('inc', 'pathauto');
      // Clean the value.
      $title_alias = pathauto_cleanstring($context['entity']->title);

      foreach($layout_render_array['ds_content'] as $field_index => $field_info) {
        if ($field_info['#field_name'] == 'title') {
          $layout_render_array['ds_content'][$field_index][0]['#markup'] = '<h2>' . l($context['entity']->title, $alias . '/' . $title_alias) . '</h2>';
          break;
        }
      }
    }
  }
}
